# Ensemble Configuration
device: "cuda" # cuda or cpu
ensemble_method: "weighted_average" # Options: 'mean', 'weighted_average', 'max_voting'
output_dir: "./outputs/ensemble_results/"
batch_size: 60
frame_skip: 30
margin: 50
min_face_size: 100

datasets:
  ASVspoof2019_LA:
    dataset_path:
    example_video_path:
  faceforensic:
    dataset_path: "./backend/dataset/FaceForensics++"
    example_video_path: "./backend/dataset/FaceForensics++/original/002.mp4"
  kaggle:
    dataset_path:
    example_video_path:
  LAV-DF:
    dataset_path:
    example_video_path:
  FakeAVCeleb:
    dataset_path: "./backend/dataset/FakeAVCeleb_v1.2"
    example_video_path: "./backend/dataset/FakeAVCeleb_v1.2/FakeAVCeleb_v1.2/RealVideo-RealAudio/African/men/id00076/00109.mp4"

# Individual Model Configurations
models:
  # EfficientNet config for the ensemble
  efficientnet_b1:
    active: true
    architecture: "efficientnet_b1"
    weights_path: "./backend/models/DeepFake_EfficientNet/faceforensic_output/outputs/checkpoints/best_model.pth"
    num_classes: 2 # Real or Fake
    image_size: 240
    ensemble_weight: 0.5
    threshold: 0.5

    # preprocessing:
    #   resize: 380
    #   normalization: "imagenet" # Standard ImageNet mean/std

  xceptionnet:

  mesonet:

  aasist:
